### ISSUE TITLE
Catch exceptions in __repr__?

### ISSUE THREAD

**Issue by benkuhn** [rollbar/pyrollbar#101]
Hi Rollbar folks, thanks for making an awesome tool!

I found myself wishing recently that Rollbar wrapped calls to `repr` inside a try/except block for whitelisted types or if `safe_repr` was turned off.

Rationale: it's very hard to ensure that `__repr__` of a whitelisted type never throws an exception. Even if I wrap the whitelisted repr in a global try/except block, someone else might come along and subclass the type with a badly-written repr that doesn't do that, for instance. And if `__repr__` *does* throw an exception, I may never learn about it since it won't come up in Rollbar!

I'd be happy to submit a PR for this if that seems reasonable to you, Rollbar devs--just wanted to check first in case there are reasons against doing this.

Thanks!

**Comment by Crisfole** [comment]
Hey, submit away! That'd be awesome.
