### ISSUE TITLE
log arguments not displayed properly on web ui

### ISSUE THREAD

**Issue by port8080** [rollbar/pyrollbar#119]
Dup of https://github.com/rollbar/pyrollbar/issues/58

@coryvirok: do you have an ETA for the fix on the UI or suggestions for workarounds?

**Comment by mikeengland** [comment]
I'd also like to see a fix for this ASAP!

**Comment by coryvirok** [comment]
Sorry for the delay. I've added an internal story to track this. We will update here once it's released.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
