### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by kivsiak** [rollbar/pyrollbar#120]
I have an aiohttp app. But the generic transport is a requests which is blocking by default. 
Is there any way to use http://aiohttp.readthedocs.io/en/stable/client.html? It's api is inspired by requests.

**Comment by ezarowny** [comment]
It could probably be added as a handler. What version of Python are you using?

**Comment by kivsiak** [comment]
Python 3.5.2

**Comment by ezarowny** [comment]
I can internally file this as a feature request for pyrollbar if you'd like (or you can take a crack at it!).

**Comment by ekampf** [comment]
👍

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
