### ISSUE TITLE
Support new Django 1.10 middleware API

### ISSUE THREAD

**Issue by twschiller** [rollbar/pyrollbar#127]
Django 1.10 introduced a new middleware API: https://docs.djangoproject.com/en/1.10/topics/http/middleware/

`MIDDLEWARE_CLASSES` is deprecated in favor of `MIDDLEWARE`.

Instructions for upgrading the middleware are at:
https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

The Travis CI configuration is already testing vs. Django 1.10. However, the Django example needs to be updated to use the new api.

**Comment by ezarowny** [comment]
We're already working on this and I'm hoping to have it out early this week.

**Comment by ezarowny** [comment]
Sorry for the delay! It's still coming.

**Comment by twschiller** [comment]
Thanks, there's no rush since Django 1.10 still supports the old API and many other middlewares haven't updated yet.

I don't have a deep understanding of Django's error model. However, there's a couple complications I see in the new API:
- Rollbar probably has to be the first MIDDLEWARE because other middlewares can short-circuit:  "If a middleware short-circuits, only that middleware and the ones before it in MIDDLEWARE will see the response."
- There's no obvious way of distinguishing whether a response is due to an exception raised in the middleware or is the expected response: "Exceptions raised from a middleware are converted to the appropriate HTTP response and then passed to the next middleware."

**Comment by ezarowny** [comment]
I'm thinking we'll have to provide two middleware classes going forwards. Django provides a nice mixin to basically backport old middleware to the new style but you have to be on Django 1.10 to actually use it.

**Comment by twschiller** [comment]
Right, I've seen other projects adopt the mixin. I'm not sure it addresses the two issues I raised in my last comment, though. As an alternative to having two middleware classes, you might be able to do one of the following with a little Python hackery:

- Dynamically mixin the class, if the mixin is available (because the user has Django 1.10 installed)
- Create a dummy mixin that provides nothing, and choose between the dummy mixin and the backport middleware dynamically

**Comment by ezarowny** [comment]
That's basically what I was getting at. We'll probably do some kind of dynamic mixin.

**Comment by Soliah** [comment]
Is there a workaround for this in the meantime? We're currently blocked as we have some middleware requiring the new API.

**Comment by ezarowny** [comment]
The workaround would be to keep the Rollbar middleware in `MIDDLEWARE_CLASSES` until the middleware is updated to be dynamic.

I'm going to try to get to this near the end of this week or the beginning of next.

**Comment by Soliah** [comment]
@ezarowny from what I can tell Django ignores `MIDLEWARE_CLASSES` if you have things in `MIDDLEWARE` so that doesn't work for us.

**Comment by ezarowny** [comment]
PR up at #138

**Comment by ezarowny** [comment]
0.13.7 has been released on PyPI. Let me know how that works for you guys.

**Comment by wli** [comment]
@ezarowny FYI I think there might be a regression: https://github.com/rollbar/pyrollbar/issues/140

**Comment by ezarowny** [comment]
Yup! Testing #141 now.
