### ISSUE TITLE
Prevent sensitive information being sent to rollbar

### ISSUE THREAD

**Issue by Soliah** [rollbar/pyrollbar#142]
Seems like this behaves very differently from the Rubygem in what data it sends to Rollbar. I'm noticing that all request headers are sent, including potentially sensitive things like the `Authorization` header.

Is there a way to stop this from being sent like the Rubygems version?

**Comment by ezarowny** [comment]
Hey @Soliah I'm pretty sure we do allow for request header scrubbing. I'll take a look.

**Comment by ezarowny** [comment]
Can you try adding a header with the name `Authentication`? It's likely we just don't have `Authorization` in the default list. You could easily add it in your config file.

**Comment by Soliah** [comment]
Ah I should've RTFM, thanks.
