### ISSUE TITLE
Message formatting

### ISSUE THREAD

**Issue by srikiraju** [rollbar/pyrollbar#143]
Is there any reason why message formatting isn't done when emitting exception type messages
In `logger.py`, `emit` method:
```
          message = record.msg
          extra_data = {
              'args': record.args,
```
This is fine for "message" type events, but for "exception" type events, we can use the full message - record.getMessage(), because the merging algorithm doesn't rely on that string.

**Comment by srikiraju** [comment]
Just saw that this was raised earlier in #125

**Comment by ezarowny** [comment]
Ah cool, I'll close this one and we can continue the discussion in there! 👍
