### ISSUE TITLE
pyramid integration not correctly parsing boolean settings

### ISSUE THREAD

**Issue by ezarowny** [rollbar/pyrollbar#146]
If you have boolean settings values in a paste config file, they will not be turned into booleans when parsing. For example, given the following config:

```
rollbar.debug = false
rollbar.verify_https = false
```

rollbar.SETTINGS will end up containing `'false'` instead of `False` for the above values.

**Comment by ezarowny** [comment]
Partial solution:

```python
def parse_settings(settings):
    prefix = 'rollbar.'
    out = {}
    for k, v in settings.items():
        if k.startswith(prefix):
            if k in BOOLEAN_SETTINGS:
                v = asbool(v)
            out[k[len(prefix):]] = v

    return out
```

Unfortunately, this will only cover top-level items. It doesn't seem like you'd be able to nest settings in paste configs though?

**Comment by coryvirok** [comment]
@ezarowny can this be closed?

**Comment by ezarowny** [comment]
Yeah, I'll update the docs for nested config items.
