### ISSUE TITLE
Support recording deployments via pyrollbar

### ISSUE THREAD

**Issue by rokob** [rollbar/pyrollbar#154]
Notifiers in other libraries support this so it should be included in this library. The basic idea is to have a library function that makes reporting to this API easy: https://rollbar.com/docs/api/deploys/#record-create-a-deploy

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
