### ISSUE TITLE
Support printing rather than reporting errors via a configuration setting

### ISSUE THREAD

**Issue by rokob** [rollbar/pyrollbar#155]
It should be easy to work with a Python project in development and testing environments with Rollbar providing useful information but not logging data to the servers. This should be configurable in the settings and support both direct API calls (`report_message`) as well as `report_exc_info`

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
