### ISSUE TITLE
Question: delete process response from Django

### ISSUE THREAD

**Issue by PabloLefort** [rollbar/pyrollbar#156]
Hi! Reading the middleware for Django i see this:
```python
    def process_response(self, request, response):
        return response
```

What is the purpose of that?
It could be removed?

Thanks!

**Comment by ezarowny** [comment]
Considering it's been that way for a while now, I imagine it has to do with the behavior difference between `MIDDLEWARE` and `MIDDLEWARE_CLASSES` (see [here](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware)). It is also possible that the `process_response` block could be removed though. You could always give it a shot!

**Comment by PabloLefort** [comment]
All rigth @ezarowny ! I'ts for backwards compatibility. But, i'll test on an old version, just for fun.
If success.. PR on the way.

Thanks

**Comment by ezarowny** [comment]
@PabloLefort what did you end up finding out? Can I close this issue?

**Comment by PabloLefort** [comment]
@ezarowny lets close it, i'll try something on this days. You will see a PR if goes well.

Thanks! :rocket:
