### ISSUE TITLE
How to pass in our own request information?

### ISSUE THREAD

**Issue by simlu** [rollbar/pyrollbar#157]
So we want to submit custom information as request information when submitting a message. How would we best do this? Generate an artificial request object? Or is there a way we could pass a dictionary?

In particular I'm talking about the report_message function here https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L359

Background: We use flask, but since we are behind several layers of passthrough, e.g. the ip reaching us is not the one we want to report on etc. Also the message is generated when the flask request object has already expired.

**Comment by rokob** [comment]
The easiest way is probably to use the payload_data parameter. This takes a dictionary which it merges with the final payload. If the request object is nil, there will be no request key in the payload dictionary, so setting `payload_data = {"request": {...}}` will not overwrite anything and will end up populating the resulting request values on the backend.

The various request types are treated differently, for instance a werkzeug request (which is basically what a Flask request is) runs through this: https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L976, so you could create your own object as the payload_data to replicate as much of that information as you desire, if your request object truly has already gone away.

**Comment by lukas-gitl** [comment]
That was great input!

This helped a lot as well: https://rollbar.com/docs/api/items_post/

Thank you. This can be closed now!
