### ISSUE TITLE
All report_exc_info are being reported as 'production' reguardless of what is in init

### ISSUE THREAD

**Issue by BossGrand** [rollbar/pyrollbar#159]
I have this simple test in one of my files and my errors are being filed under 'production' reguardless of what go into the init

     import rollbar
     rollbar.init(settings.ROLLBAR_KEY, 'development')

     try:
         raise Exception('simple test')

    except Exception as e:
         rollbar.report_exc_info()

**Comment by ezarowny** [comment]
I cannot replicate this. It's working as intended for me.

```python
import rollbar

rollbar.init('some_key', 'some_env')

rollbar.report_message('message test')

try:
    1 / 0
except:
    rollbar.report_exc_info()
```

**Comment by ezarowny** [comment]
Have you called init anywhere before this? Maybe in the initialization of your shell (via your web framework)?

**Comment by BossGrand** [comment]
That is probably what is happening, I'm getting a message in my console
that roll bar has already been initialized and that it is ignoring.

Thank you for the insight you can probably close this I'll post my findings
if there are any

**Comment by BossGrand** [comment]
@ezarowny, ok it was related to my log handler

        'rollbar': {
            'access_token': ROLLBAR_KEY,
            'environment': 'production',
            'class': 'rollbar.logger.RollbarHandler'
        },

this was already initializing rollbar to have the environment of "production", so my other inits were ignored
