### ISSUE TITLE
Pyramid: Add`authenticated_userid` to search of request to automatically enable people tracking

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/pyrollbar#161]
From an inquiry sent to Rollbar support:

> I use the Pyramid (Python) framework, and if I read it correctly if you added "authenticated_userid" to your search of the 'request' you'd get automatic Pyramid support too!
> http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.authenticated_userid
> Is that something you could add?

**Comment by ezarowny** [comment]
We'd probably just need to add it to https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L691.

**Comment by ezarowny** [comment]
Testing this on my development machine returns `23|1605f03f8f2044cfb4a54b7fe2ed6fcb`. My user's id is 23 so we can probably just split on the pipe symbol here.

**Comment by brianr** [comment]
@ezarowny I think in stock pyramid, authenticated_userid would just return the actual user id (e.g. `23`).

**Comment by vrtual** [comment]
Depends what you're using for a userid, see pyramid.security.remember
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/security.html

I use an email address, so when I ask for authenticated_userid I get the email addr I stored with 
headers = remember(request, userEmail)

So you'd probably have to return the whole thing, and let the end user work it out depending on what they're using for an authentication policy.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by duncanw** [comment]
Hi there, did this change ever get implemented?
If not, I would be interested in it. Thanks!
