### ISSUE TITLE
Twisted should not install log handler automatically

### ISSUE THREAD

**Issue by gdoermann** [rollbar/pyrollbar#163]
Rollbar automatically installs the log observer for twisted upon import.  This is a massive issue if you never initialize rollbar or if the initialization fails. The log observer should be added *after* you call `rollbar.init(handler='twisted', **settings.ROLLBAR)` so that you can verify it will work before sending messages to the observer.  If you do not initialize rollbar the observer will receive messages but will err out until it completely blocks the twisted loop.

**Comment by ezarowny** [comment]
Ah, nice find! Thanks!

**Comment by ezarowny** [comment]
I'll take a crack at this.

**Comment by rokob** [comment]
Why does sending messages to the observer that is uninitialized cause problems? Shouldn't that just be a no-op?

**Comment by gdoermann** [comment]
We were having issues with twisted freezing when using rollbar client (in twisted mode). At first we just stopped initializing rollbar but it did not fix it because twisted was running so the rollbar observer was running and throwing a lot of errors saying we needed to initialize before trying to send.

**Comment by ezarowny** [comment]
Could you give #171 a try for me?

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
