### ISSUE TITLE
Infinite loop in Twisted handler

### ISSUE THREAD

**Issue by ezarowny** [rollbar/pyrollbar#172]
Certain types of network errors will cause pyrollbar to get into a loop when using the Twisted handler. One such type of network error is to point pyrollbar's endpoint somewhere with an invalid or self-signed certificate.

Basically, our treq network call reports an error into Twisted logging system that doesn't get recognized as an internal error.  As a result, the observer ends up calling report_exc_info which gets reported into Twisted's logging system and so on.

If you're a Rollbar employee, the easiest way to cause this error to get trapped in the reactor is to try and send an error to your dev vm using the HTTPS endpoint. Twisted doesn't like self-signed certs.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
