### ISSUE TITLE
provide hook to modify payload before sending

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/pyrollbar#183]
details in https://app.clubhouse.io/rollbar/story/9481/pyrollbar-provide-hook-to-modify-payload-before-sending

**Comment by jtsoi** [comment]
We have the same issue. 
Solved it this way for now:

```
import rollbar as patched_rollbar

_original = patched_rollbar._build_django_request_data


def wrapper(request):
    request_data = _original(request)
    request_data['request_id'] = request.uuid
    return request_data

patched_rollbar._build_django_request_data = wrapper

```

A suggestion would be to put the hook on the rollbar module and not in the middleware.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
