### ISSUE TITLE
Django Rest Framework POST params

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/pyrollbar#186]
Details in https://app.clubhouse.io/rollbar/story/4586

**Comment by nfortenberry** [comment]
Are there any updates on this?  I've noticed there is a pull request that solves this that has been open since Dec 2015. https://github.com/rollbar/pyrollbar/pull/86

**Comment by rivkahstandig3636** [comment]
Hi @nfortenberry, the latest release of this SDK addresses this issue. Closing the issue now.
