### ISSUE TITLE
Cut a new release to PyPI with new AWS lambda_function code

### ISSUE THREAD

**Issue by levi-rs** [rollbar/pyrollbar#193]
Rollbar announced support for AWS python lambda functions:
https://changelog.rollbar.com/support-for-python-on-aws-lambda-34007

However, the release currently on PyPI (0.13.12) is from July 3, and does not include the new `lambda_function` decorator that is used in the documentation example.

Could you possibly deploy a new minor version that includes the `lambda_function` decorator?

**Comment by rokob** [comment]
0.13.13 is out
