### ISSUE TITLE
aiohttp request data support

### ISSUE THREAD

**Issue by homm** [rollbar/pyrollbar#195]
I have aiohttp app and `rollbar.logger.RollbarHandler` error handler. I don't see many useful information about requests in error reports, which I see for Tornado applications, for example. There are:

request.headers
request.method
request.url
request.GET
request.start_time
request.user_ip

This makes rollbar very limited with aiohttp applications.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
