### ISSUE TITLE
Chained exceptions are not properly shown in Rollbar GUI

### ISSUE THREAD

**Issue by simonpercivall** [rollbar/pyrollbar#196]
Not clear to me why this is a `pyrollbar` issue, but was sent here by the support.

Rollbar exception reporting for chained exceptions should follow the method described in [PEP 3134](https://www.python.org/dev/peps/pep-3134/#enhanced-reporting), to describe the relationship between chained exceptions (i.e. cause and context).

Currently the exceptions are displayed without any clarification on _how_ they are related in the chain, and also in opposite order of how the default Python exception handler displays exceptions (which, of course, makes the lack of description of the relationship between exceptions even more problematic).

Thanks!

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
