### ISSUE TITLE
Rollbar is raising errors when running Django permission tests

### ISSUE THREAD

**Issue by mikemanger** [rollbar/pyrollbar#199]
I have some simple permission tests to make sure users can not access certain sections of the site. For example:

```
from django.test import TestCase, Client
from django.core.urlresolvers import reverse

class PermissionsTestCase(TestCase):
    def test_logged_out_list_view(self):
        client = Client()
        response = client.get(reverse('list_view'))
        self.assertEqual(response.status_code, 403)
```

The tests run fine (logged out users can not access `list_view`) however I am getting `PermissionDenied` errors in rollbar. This is odd because the [test client shouldn't raise this exception](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#exceptions).

**Comment by ohmanger** [comment]
Not ideal but a work around is to disable Rollbar in a custom test settings file.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
