### ISSUE TITLE
API error: Invalid format. data.body.trace.frames is missing and it is required. data.body.trace.exception.class is missing and it is required.

### ISSUE THREAD

**Issue by inkmix** [rollbar/pyrollbar#201]
We're getting this error since upgrading from `0.13.11` to `0.13.13`.
(this issue https://github.com/rollbar/pyrollbar/issues/197 looks similar)

We're using the django rollbar handler and not the middleware. This happens not for all but for some exceptions sent to rollbar.
I noticed that the `body` payload that is sent includes both `trace` and `trace_chain` but the rollbar documentation says, to only send one ("// Required: "trace", "trace_chain", "message", or "crash_report" (exactly one)"). The `trace` part for those errors seem to always look like:

```
      "trace": {
        "exception": {
          "description": "meaningful description here"
        }
      },
```

*edit:*
this is how we create the handler:
```
        'rollbar': {
            'level': 'WARNING',
            'class': 'rollbar.logger.RollbarHandler',
            'history_level': 'WARNING',
        },
```

We downgraded for now. Let me know if any more information can help you.

**Comment by rokob** [comment]
Hmm yeah definitely should not include both trace and trace_chain, will try to bisect between 0.13.11 and 0.13.13 to see if I can find out what this is.

**Comment by inkmix** [comment]
thank you @rokob :)

**Comment by rokob** [comment]
0.13.15 is released with a change that should fix this

**Comment by inkmix** [comment]
perfect, I'll try it out and let you know in case we experience further issues.

**Comment by inkmix** [comment]
FYI: we still had this issue with the 0.13.16 -- I haven't found enough time to properly reproduce it and report it back. we saw this
> Fix bug where both trace and trace_chain could appear in the final payload, which is not allowed by the API.
in release notes of 0.13.17. maybe that fixes it :) I'm going to try this in following days.

**Comment by sallyruthstruik** [comment]
Faced similar problem. Be sure, that you don't send 'body' in logger extra, f.e.

```
logger.error('message', extra={'body': 'some body'})
```

In our case it was a reason of error.
