### ISSUE TITLE
Why are local variables not working? 

### ISSUE THREAD

**Issue by and-megan** [rollbar/pyrollbar#216]
They're not showing up in the frames at all with this config:

ROLLBAR = {
    'access_token': ROLLBAR_ACCESS_TOKEN,
    'environment': CURRENT_ENVIRONMENT,
    'root': ROOT_DIR,
    'enabled': True if ROLLBAR_ACCESS_TOKEN else False,
    'locals': {
        'enabled': True,
        'safe_repr': False,
    }
}

pyrollbar 0.13.16

https://app.intercom.io/a/apps/rlisg82q/respond/inbox/813342/conversations/12599019578

**Comment by rokob** [comment]
There is some code to gracefully not blow up and still send the item if something goes wrong while adding the local variables. There is also code that performs transforms (scrubbing and shortening) of the local data. It is possible there is a bug in that transformation code or how it is configured, or there is something unique about these frames that we are not getting the locals out properly. That is the configuration that should work for adding locals, and the basic code paths that look at that configuration (i.e. enabled or not) looks right.
