### ISSUE TITLE
Allow ignoring of python logging levels

### ISSUE THREAD

**Issue by oliver-zhou** [rollbar/pyrollbar#230]
When using the rollbar middleware in Django, it seems all 'INFO' logging messages are recorded as events in rollbar, consuming events for items that were never meant to be events, but were meant to be debug type statements. 

How can I control what level of python logging library events get logged by rollbar? 

For example, how can I record 'WARNING', 'ERROR' level logging events, but ignore 'DEBUG' and 'INFO' level messages from being sent to rollbar?

**Comment by oliver-zhou** [comment]
Oops, I figured it out. 

Since its a Django logging setting, all I had to do was set level
```
        'rollbar': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'access_token': 'f2fab09b88114ac7aec92dcf16e905a4',
            'environment': 'production',
            'class': 'rollbar.logger.RollbarHandler'
        },

```

**Comment by rivkahstandig3636** [comment]
Glad you were able to figure it out!
