### ISSUE TITLE
Rollbar reinitializing when using LOGGING in Django

### ISSUE THREAD

**Issue by pembo13** [rollbar/pyrollbar#231]
I'm trying to use the LOGGING configuration method in Django+Celery and I'm having a couple issues, first of which is that Rollbar gets double initialized when using LOGGING, resulting in:

`WARNING:rollbar:Rollbar already initialized. Ignoring re-init.`

Really, I’m looking for a working example of using LOGGING in a project with Django and Celery such that I do not need MIDDLEWARE, and do not get any warnings – and I can have all uncaught exceptions caught from both frameworks, as well as manually trigger log errors.

**Comment by pembo13** [comment]
Sample `LOGGING`

`LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'filters': {
		'require_debug_false': {
			'()': 'django.utils.log.RequireDebugFalse',
		},
		'require_debug_true': {
			'()': 'django.utils.log.RequireDebugTrue',
		},
	},
	'handlers': {
		'console': {
			'level': 'INFO',
			'filters': ['require_debug_true'],
			'class': 'logging.StreamHandler',
		},
		'mail_admins': {
			'level': 'ERROR',
			'filters': ['require_debug_false'],
			'class': 'django.utils.log.AdminEmailHandler'
		},
		'rollbar': {
			'filters': ['require_debug_false'],
			'access_token': ERRORTRACKING_SERVERTOKEN,
			'environment': 'production',
			'class': 'rollbar.logger.RollbarHandler'
		},
	},
	'loggers': {
		'django': {
			'handlers': ['console', 'mail_admins', 'rollbar'],
			'level': 'INFO',
			'propagate': True,
		},
	},
}`

**Comment by pembo13** [comment]
Real application `LOGGING`

    LOGGING = {
        'disable_existing_loggers': False,
        'version': 1,

        'filters': {
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse',
            },
            'require_debug_true': {
                '()': 'django.utils.log.RequireDebugTrue',
            },
        },

        'formatters': {
            'django.server': {
                '()': 'django.utils.log.ServerFormatter',
                'format': '[%(server_time)s] %(message)s',
            }
        },

        'handlers': {
            'console': {
                'level': 'INFO',
                'filters': ['require_debug_true'],
                'class': 'logging.StreamHandler',
            },
            'django.server': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'django.server',
            },
            'mail_admins': {
                'class': 'django.utils.log.AdminEmailHandler',
                'filters': ['require_debug_false'],
                'level': 'ERROR',
            },
            'rollbar': {
                'class': 'rollbar.logger.RollbarHandler',
                'filters': ['require_debug_false'],
                
                'access_token': ERRORTRACKING_SERVERTOKEN,
                'environment': ROLLBAR_ENVIRONMENT,

                'code_version': git.get_code_version(BASE_DIR),
                'branch': git.get_branch(BASE_DIR),
                'root': BASE_DIR,

                'patch_debugview': False,

                'exception_level_filters': [
                    (Http404, 'ignored'),
                    (PermissionDenied, 'ignored'),
                ]
            },
        },

        'loggers': {
            'celery': {
                'handlers': ['console', 'rollbar'],
                'level': 'DEBUG' if DEBUG else 'INFO',
                'propagate': False,
            },
            'celery.bootsteps': {
                'handlers': ['console', 'rollbar'],
                'level': 'DEBUG' if DEBUG else 'INFO',
                'propagate': False,
            },

            'django': {
                'handlers': ['console', 'mail_admins'],
                'level': 'INFO',
            },
            'django.server': {
                'handlers': ['django.server'],
                'level': 'INFO',
                'propagate': False,
            },

            'project': {
                'handlers': ['console'],
                'level': 'DEBUG' if DEBUG else 'ERROR',
            },
            'project.commands': {
                'handlers': ['console', 'mail_admins'],
                'level': 'DEBUG' if DEBUG else 'ERROR',
                'propagate': False,
            },
            'project.utils': {
                'handlers': ['console', 'mail_admins'],
                'level': 'DEBUG' if DEBUG else 'ERROR',
                'propagate': False,
            },
        }
    }

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by pembo13** [comment]
I can confirm, it's still an issue. On a related note, a sample config using LOGGER in a project with both Django and Celery would very much be appreciated.

**Comment by pembo13** [comment]
@rivkahstandig3636 any updates on this?

**Comment by pembo13** [comment]
@rokob that helps, thanks.

Django+Celery is a popular enough combo to warrant a Rollbar sample I think. Plus, a few releases ago, Celery removed email error notifications.

**Comment by rokob** [comment]
So I have https://github.com/rokob/rollbar-django-celery which uses the LOGGING infrastructure to report items to Rollbar rather than the Django middleware and captures uncaught exceptions in both Celery tasks as well as in Django requests. One way to avoid the double initialization issue is to initialize rollbar directly, and then not pass an access token in the LOGGING configuration (https://github.com/rokob/rollbar-django-celery/blob/master/rbexample/settings.py#L119,L142).

**Comment by jessewgibbs** [comment]
Closing this issue since the original question appears to be addressed by the example mentioned above.

**Comment by pembo13** [comment]
@rokob I commented #251, I'm running into issues with the sample.
