### ISSUE TITLE
"See Release Notes"

### ISSUE THREAD

**Issue by MacMcIrish** [rollbar/pyrollbar#232]
Rollbar 0.13.18 changelog says "See Release Notes". At the time of creating this issue, there are no release notes for 0.13.18.

https://github.com/rollbar/pyrollbar/releases/tag/v0.13.18

**Comment by rokob** [comment]
Yeah sorry doing that today

**Comment by dmitry-mukhin** [comment]
Are you completely dumping changelog.md in favour of github releases?
Seems like a bad move.

**Comment by rivkahstandig3636** [comment]
@dmitry-mukhin Yes, we are.
