### ISSUE TITLE
Django 2.0 - module 'django.views.debug' has no attribute 'TECHNICAL_500_TEMPLATE'

### ISSUE THREAD

**Issue by HappyTepid** [rollbar/pyrollbar#233]
Since upgrading my project to Django 2.0, the following error gets thrown when starting the server:

``ERROR:rollbar.contrib.django.middleware:Rollbar - unable to monkeypatch debugview to add 'View in Rollbar' link. To disable, set `ROLLBAR['patch_debugview'] = False` in settings.py. Exception was: AttributeError("module 'django.views.debug' has no attribute 'TECHNICAL_500_TEMPLATE'",)``

Errors still get logged in Rollbar, but the 'View in Rollbar' link no longer appears on Django's error page.

It doesn't seem to be project-specific as I get the same error if I create a fresh Django 2.0.2 project with just Django and Rollbar in my venv.

**Comment by brianr** [comment]
Thanks @HappyTepid for the report; looks like we need to update the feature that patches that template for django 2.0.

As a workaround, you can disable it via the config flag `patch_debugview`, e.g.:

```
ROLLBAR = {
    'access_token': 'your token here',
    'patch_debugview': False,
    # ... any other config params ...
}
```
