### ISSUE TITLE
Create sample config using LOGGER in a Django & Celery project

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/pyrollbar#251]
Requested in #231

**Comment by pembo13** [comment]
@rivkahstandig3636 following the sample project as an example, I get `pyrollbar: No access_token provided. Please configure by calling rollbar.init() with your access token` when an uncaught exception occurs.

**Comment by jessewgibbs** [comment]
@rokob can you take a look at this when you get a chance?

**Comment by rokob** [comment]
Did you catch the init call possibly hidden in the settings file: https://github.com/rokob/rollbar-django-celery/blob/master/rbexample/settings.py#L119,L120

**Comment by jessewgibbs** [comment]
@pembo13 I'm going to close this issue.  If you're still encountering this issue, please let us know.
