### ISSUE TITLE
Django Environment not posting to rollbar

### ISSUE THREAD

**Issue by villanuevawill** [rollbar/pyrollbar#252]
https://github.com/Bounties-Network/BountiesAPI/blob/master/bounties_api/bounties/settings.py - it's on this repo - open source.  I followed the django instructions.

```
ROLLBAR = {
  'access_token': rollbar_token,
  'environment': ENVIRONMENT,
  'root': os.getcwd(),
  'enabled': True if rollbar_token else False,
}
```

`rollbar.contrib.django.middleware.RollbarNotifierMiddleware` is added to middleware

Environment is not getting passed through. Requirements.txt:

```
Django>=1.8,<2.0
psycopg2
redis==2.10.6
djangorestframework==3.7.7
web3==3.16.5
ipfsapi==0.4.2
boto3==1.5.35
rollbar==0.13.18
slackclient==1.1.2
djangorestframework-filters==0.10.2
django-cors-headers==2.2.0
requests==2.18.4
uwsgi==2.0.17
django-nose==1.4.5
coverage==4.5.1
codecov==2.0.15
```

**Comment by rivkahstandig3636** [comment]
We'll take a look into this. Thanks for reporting the issue!

**Comment by rokob** [comment]
It looks like having the LOGGING setup: https://github.com/Bounties-Network/BountiesAPI/blob/master/bounties_api/bounties/settings.py#L144,L148 is causing environment to get set to `None`. If you set `environment: ENVIRONMENT` in the rollbar logging setup, then the environment should get set correctly. That seems to be the immediate cause. I don't know enough about the Django contrib stuff to know how the middleware and the LOGGING handler are meant (or not) to interact.
