### ISSUE TITLE
Ability to set requests.Session() pool size

### ISSUE THREAD

**Issue by CapCap** [rollbar/pyrollbar#274]
Currently in our app we're doing the following as during startup some of our services emit a lot of (important) debug data at a rate that exceeds the default request pool size, so this is our workaround (in our custom `logging.Handler` rollbar wrapper)

It would be great if we could pass something like this through the `rollbar.init` params. I can create a PR if you guys think this is something you want.

```python
import requests
import rollbar.lib.transport as tr
tr._session().mount('https://', requests.adapters.HTTPAdapter(max_retries=3, pool_connections=10, pool_maxsize=20))
tr._session().mount('http://', requests.adapters.HTTPAdapter(max_retries=3, pool_connections=10, pool_maxsize=20))
```

**Comment by rivkahstandig3636** [comment]
@CapCap PRs are always welcome!
