### ISSUE TITLE
blocking handler doesn't work in most basic example

### ISSUE THREAD

**Issue by peterbe** [rollbar/pyrollbar#280]
I was trying to get [`django-rq`](https://github.com/rq/django-rq) with `rollbar` but instead of creating my own worker using [this tip](https://github.com/rollbar/pyrollbar/blob/18b40e6b8c94864dc0832c8f617aa42f829fa2da/rollbar/contrib/rq/__init__.py#L2-L30) I defined my own custom worker class, which inside the `__init__`, calls `rollbar.init(...)` and set a custom exception handler function. 

I thought I had everything working but messages were never received. The instructions in `rollbar.contrib.rq.__init__` warns that you need to use `handler="blocking"` because (the default) `handler="thread"` doesn't work there. 

So I tested like this:

```
>>> import os
>>> access_token=os.environ.get('ROLLBAR_ACCESS_TOKEN')
>>> assert access_token
>>> import rollbar
>>> rollbar.init(access_token, 'development')
>>> try:
...   a=b
... except Exception:
...   rollbar.report_exc_info()
...
```
That worked! I got an email from Rollbar within seconds and the exception was in my dashboard. 

Now, exact same thing but with `handler="blocking"`:

```
>>> import os
>>> access_token=os.environ.get('ROLLBAR_ACCESS_TOKEN')
>>> assert access_token
>>> import rollbar
>>> rollbar.init(access_token, 'development', handler='blocking')
>>> try:
...   c=d
... except Exception:
...   rollbar.report_exc_info()
...
```

Nothing happened :(

**Comment by peterbe** [comment]
Scratch that!

I totally is there. I fumbled in the UI. It got (correctly!) lumped with the previous `NameError` exception when I tested with `handler="thread"`.

**Comment by rivkahstandig3636** [comment]
Glad you were able to figure it out :)
