### ISSUE TITLE
Ignore exceptions in Pyramid middleware?

### ISSUE THREAD

**Issue by luhn** [rollbar/pyrollbar#289]
I have certain exceptions that I expect to happen and catch using an error view to produce a helpful response.  For example, something like this:

```python
@view_config(context=ExpiredTokenException)
def expired_token(context, request):
    return HTTPFound(request.resource_path(SIGNIN_URL))
```

Even though this error is handled, Rollbar sees the ExpiredTokenException in `request.exception` and reports the error to Rollbar.  (Which is somewhat [my fault](https://github.com/rollbar/pyrollbar/pull/162))  I'd like a way to ignore these errors.  A few ideas:

* Have a request property to tell Rollbar to ignore it.  e.g., `request.ignore_exception`
* A configurable EXCEPTION_WHITELIST and EXCEPTION_BLACKLIST

I'm willing to do the legwork on this, but wanted to get some feedback first.

(I've tried doing `request.exception = None`in my error view, but Pyramid overrides it.)

**Comment by jessewgibbs** [comment]
@luhn thanks for the suggestion.

@rokob what are your thoughts on this?

**Comment by rokob** [comment]
We have the configuration variable `exception_level_filters` https://docs.rollbar.com/docs/python#section-configuration-reference which allows you to set levels but also to ignore completely exceptions by their class. So you could add `(ExpiredTokenException, 'ignored')` to this configuration setting to get the blacklist you are looking for.

**Comment by rokob** [comment]
If the exception_level_filters` is not enough, we could add the ability to set EXCEPTION_BLACKLIST and EXCEPTION_WHITELIST from the settings file.

**Comment by jessewgibbs** [comment]
@luhn I'm going to close this issue since @rokob provided a solution above.  If you have further questions, please let us know.

**Comment by luhn** [comment]
No problem.  @rokob's solution looks like it'll work for me.  Thanks guys!
