### ISSUE TITLE
Connection pool is full, discarding connection: api.rollbar.com

### ISSUE THREAD

**Issue by amirouche** [rollbar/pyrollbar#293]
We are seeing the following message in rollbar:

> Connection pool is full, discarding connection: api.rollbar.com

It's harmless but I would like to understand.

It's urllib3 (via requests) that emits the message: 

https://github.com/urllib3/urllib3/blob/cd7cfa613b2678e700597d098ce9bbdc934863e6/src/urllib3/connectionpool.py#L250-L274

I am not sure how this can happen since the program doesn't hit a lot of domains, my understanding is that the connection pool should not be full.

Anybody experience that error?

**Comment by jessewgibbs** [comment]
Hey @amirouche,

Not sure if this is an issue w/ pyrollbar or not, but I'll put this into the backlog for our SDK maintainers to review.

**Comment by amirouche** [comment]
I am using 0.13.8 upgrading to 0.14.5 then the error disappears. I think this commit 27cc77afba40e36ffd02c37f0f63c57f3e572128 fix the issue, but I am not sure.

I think it's also related to the fact that we were hiting a rollbar rate limit.

Anyway, the good news is that pyrollbar works just fine.
