### ISSUE TITLE
Rollbar drops stack trace and instead reports APIError

### ISSUE THREAD

**Issue by rex-remind101** [rollbar/pyrollbar#296]
Ever error from this code
```
def lambda_handler(event, context):
    try:
        handle_event(event)
        return rollbar.wait()
    except:
    // Should end up here.
        if is_debug_log_level():
            print(sys.exc_info())
        rollbar.report_exc_info()
        rollbar.wait()
        raise
```

Results in this error on rollbar
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/rollbar/__init__.py", line 1336, in _send_payload
_post_api('item/', payload_str, access_token=access_token)
File "/var/task/rollbar/__init__.py", line 1387, in _post_api
return _parse_response(path, SETTINGS['access_token'], payload_str, resp)
File "/var/task/rollbar/__init__.py", line 1545, in _parse_response
raise ApiError(json_data.get('message') or 'Unknown error')
rollbar.ApiError: Invalid format. data.body should be object. data.body must have exactly one of the properties: 'trace', 'trace_chain', 'message', or 'crash_report'.
```
Which is very difficult to work with.

This is from an AWS lambda run.

**Comment by brianr** [comment]
Hi @rex-remind101 - thanks for the report! Looks like pyrollbar is generating an invalid payload for some reason.

Could you send a quick note to support@rollbar.com with a link to your project in Rollbar? I think there will be some more information there that will help debug this more easily.

**Comment by jessewgibbs** [comment]
Internal conversation: https://app.intercom.io/a/apps/rlisg82q/conversations/19556865590?redirectTo=feed

**Comment by jessewgibbs** [comment]
@rokob could you take a look into this issue?  There's some additional conversation w/ the support team at https://app.intercom.io/a/apps/rlisg82q/conversations/19556865590.

**Comment by jessewgibbs** [comment]
I think this issue was resolved via the support conversation.  If not, please re-open and let us know.
