### ISSUE TITLE
Make blacklisted_local_types configurable

### ISSUE THREAD

**Issue by coryvirok** [rollbar/pyrollbar#30]
We want to allow the user to configure the `blacklisted_local_types` object. Currently, this is only done by `rollbar.contrib.django` when it's imported.

**Comment by rokob** [comment]
A bigger issue here is that `blacklisted_local_types` still exists as a list in the code, but it is never used anywhere. It appears that the blacklist idea was converted into the idea of safe_repr which is basically a whitelist. The change that stopped using `blacklisted_local_types` was https://github.com/rollbar/pyrollbar/pull/75. So I'm going to close this issue by cleaning up the existence of that list including modifying it in the Django contrib code in favor of the existing whitelist and safe_repr options.
