### ISSUE TITLE
Rollbar not reporting containerized django

### ISSUE THREAD

**Issue by kos08001** [rollbar/pyrollbar#302]
Followed the rollbar guide and sample django app. No able to get rollbar to report any issues. Able to use send_message() inside django shell however.

**Comment by kos08001** [comment]
@pembo13

**Comment by jessewgibbs** [comment]
@kos08001 what version of Django are you running, and what are the OS and container you're using?

**Comment by kos08001** [comment]
> @kos08001 what version of Django are you running, and what are the OS and container you're using? Django==2.0.2, Container=python:3.6

**Comment by jessewgibbs** [comment]
@jessicahsieh can you see about reproducing this issue?

@kos08001 can you provide us some more code snippets of how you're instantiating and then calling Rollbar?

**Comment by kos08001** [comment]
@jessewgibbs 
The dockerfile contains standard practice for a django app.
## Below is the docker-compose section of the app.

`project_server:`
&nbsp;&nbsp;&nbsp;&nbsp; `env_file: .env`
&nbsp;&nbsp;&nbsp;&nbsp; `command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PROJECT_PORT}"`

   &nbsp;&nbsp;&nbsp;&nbsp;`container_name: project_server`
    &nbsp;&nbsp;&nbsp;&nbsp;`build:`
  &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;`context: .`
      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;`dockerfile: dockerfiles/django/dev/Dockerfile`
  &nbsp;&nbsp;&nbsp;&nbsp;  `volumes:`
     &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;`- .:/project`
 &nbsp;&nbsp;&nbsp;&nbsp;  `environment: `
      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;`- DEBUG:TRUE`
  &nbsp;&nbsp;&nbsp;&nbsp;  `ports:`
     &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;` - "${PROJECT_PORT}:${PROJECT_PORT}"`
   &nbsp;&nbsp;&nbsp;&nbsp; `network_mode: "host"`

## Project settings file:
`MIDDLEWARE = [
...,
    "rollbar.contrib.django.middleware.RollbarNotifierMiddleware",
]`

`ROLLBAR = {`
 &nbsp;&nbsp;`"access_token": "OUR_POST_SERVER_ITEM_ACCESS_TOKEN",`
 &nbsp;&nbsp;` "environment": "development" if DEBUG else "production",`
 &nbsp;&nbsp; `"root": BASE_DIR,`
 &nbsp;&nbsp; `"patch_debugview": False`
`}`
`import rollbar`
`rollbar.init(**ROLLBAR)`

## Project celery file:

`import rollbar`
`if 'celery' in sys.argv:`
&nbsp;&nbsp;&nbsp;&nbsp; `rollbar.BASE_DATA_HOOK = celery_base_data_hook`

`@task_failure.connect`
`def handle_task_failure(**kw):`
&nbsp;&nbsp;&nbsp;&nbsp; `rollbar.report_exc_info(extra_data=kw)`

**Comment by kos08001** [comment]
@jessewgibbs was your team able to replicate this?

**Comment by jessicahsieh** [comment]
@kos08001
I was able to get rollbar working with Django but haven't set it up with celery yet. I'll look into it today

**Comment by kos08001** [comment]
@jessicahsieh I was as well just not with celery.

**Comment by jessewgibbs** [comment]
@rokob any quick ideas as to what could be going on here?  So far we've not had luck in getting Celery to work within the Docker environment.

**Comment by rokob** [comment]
If I am reading this correctly, you want to send a message to Rollbar when a celery task fails, is that correct? By default we use a separate thread to send items, so your process might exit before the item has a chance to send because `report_exc_info` returns before the item has actually been sent to the API. You can set the `handler` in your configuration to `blocking` which will cause the `report_exc_info` function to only return after the item has been sent, or you can call `rollbar.wait()` before your process would normally exit to block until all items have sent.

**Comment by brianr** [comment]
@kos08001 ping - have you had a chance to try what @rokob suggested? ^

**Comment by danielmorell** [comment]
I am going to close this issue because of inactivity.
