### ISSUE TITLE
Meaningless message reported on HttpResponseBadRequest

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/pyrollbar#311]
`pyrollbar` reports ` %s: %s (/Library/Frameworks/Python.framework/Versions/*/lib/python*/site-packages/django/utils/log.py:log_response)` when the `HttpResponseBadRequest` is returned from the view in Django projects.

**Comment by mihow** [comment]
We are seeing thousands of these too. At least one is reported in every request.

**Comment by letaniaferreira** [comment]
Another customer being affected - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/23968040747

**Comment by letaniaferreira** [comment]
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/23996145175

**Comment by mihow** [comment]
We are seeing these for every Django 404

**Comment by ymguerra** [comment]
Hi, I know this issue is closed but in our project we are having this problem a lot:
`/opt/virtualenv*/apic*/lib/python*/site-packages/django/utils/log.py:log_response` 

We are using python 3.6.9, Django 2.2 and rollbar 0.15.0, this problem start after we migrate from Django 1.11 to 2.2 a few weeks ago, any idea?

**Comment by waltjones** [comment]
@ymguerra What is the full message string you're seeing?

**Comment by ymguerra** [comment]
HI @waltjones , he name of the rollbar error on my dashboard is: `#5471 %s: %s (/opt/virtualenv*/apic*/lib/python*/site-packages/django/utils/log.py:log_response)`

and the message is `%s: %s`

**Comment by ymguerra** [comment]
Hi @waltjones, sorry to bother you, but do you have any idea?

**Comment by waltjones** [comment]
Hi @ymguerra I'll be taking a closer look at this today, and will follow up here as soon as possible.

**Comment by waltjones** [comment]
@ymguerra Can you send dashboard URL for the relevant project to walt.jones@rollbar.com?
