### ISSUE TITLE
Add Person data to python logging without using a web framework

### ISSUE THREAD

**Issue by jamwil** [rollbar/pyrollbar#321]
This is a similar issue to #320 

I'm looking to add Person data to a desktop application with no explicit request object. I have tried injecting a custom attribute directly into the LogRecord with the code below, however no request object is coming through. The documentation is a little sparse on what a `request` object is when outside of the confines of a given web framework. My application is a desktop client application and I'm looking to log the USERNAME environment variable to Rollbar's People tracking functionality.

```python
old_factory = logging.getLogRecordFactory()

def record_factory(*args, **kwargs):
    record = old_factory(*args, **kwargs)
    record.request = {"rollbar_person": "some user"}
    return record

logging.setLogRecordFactory(record_factory)
```

Likewise, I have tried setting ```BASE_DATA_HOOK``` using the methodology in #320 and this additional snippet to the hook function:
```python
data["rollbar_person"] = "user id"
```

I feel like I'm missing something rudimentary.

**Comment by brianr** [comment]
Hi @jamwil - the `rollbar_person` param needs to be a property of the object, not a dictionary element. I think this may work:

```
class SimpleRequestWithPerson(object):
    def __init__(self, person_dict):
        self.rollbar_person = person_dict

def record_factory(*args, **kwargs):
    record = old_factory(*args, **kwargs)
    record.request = SimpleRequestWithPerson({'id': 'id_as_a_string', 'username': 'the_username', 'email': 'email@example.com'})
    return record

logging.setLogRecordFactory(record_factory)
```

**Comment by jamwil** [comment]
Thanks @brianr! I'll give this a try.

**Comment by jamiesandenr** [comment]
Thanks to @brianr for this.  I've just spent a good deal of time trying to work out how to do the above before finding this issue.  It would be nice if the documentation be made clearer to explain what the `request` argument is expecting to receive.  Currently the dosctring for `report_exc_info` just says "request: optional, a WebOb, Werkzeug-based or Sanic request object"  which is less than useful.
