### ISSUE TITLE
Support for Startllete / ASGI

### ISSUE THREAD

**Issue by letaniaferreira** [rollbar/pyrollbar#324]
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813342/conversations/24375236669

**Comment by tedmiston** [comment]
Cross-linking with https://github.com/rollbar/pyrollbar/pull/369 which mentions forthcoming support for FastAPI.

**Comment by bxsx** [comment]
We've released v0.16.0 with ASGI / Starlette / FastAPI support. You can update pyrollbar to the latest version (v0.16.1 as I write it) via pip and try it out: `pip install -U rollbar`

Documentation is available at https://docs.rollbar.com/docs/python
