### ISSUE TITLE
Consider building wheel

### ISSUE THREAD

**Issue by Behoston** [rollbar/pyrollbar#330]
You should consider building wheel package.
https://pythonwheels.com/
I don't readed rollbar code, I don't know if is possible to create wheel easily, but I can't find discussion about wheel.

rollbar is last package without wheel in my project

**Comment by Far3t** [comment]
Bumping this issue to know if this is something you plan to do?
This is an issue I have when using Rollbar with Chalice as the chalice packager is checking if the package has a wheel or not.

**Comment by danielmorell** [comment]
This request has been resolved for a bit, but we never circle back. Sorry, about that! We are now publishing wheels along with the source distribution to PyPI.
