### ISSUE TITLE
pypi/release is out of date (commits to master are over a year old)

### ISSUE THREAD

**Issue by terencehonles** [rollbar/pyrollbar#332]
The [last release](https://github.com/rollbar/pyrollbar/releases/tag/v0.14.7) is over a year old, and the fix such as #312 (for #311) has not been released yet. I spent too much time debugging why this was still happening for me until I realized I wasn't actually looking at the code I thought I was running.

I added #331 to update that this package does work in newer versions of Python, but the tests have not been updated to support additional environments in awhile. I was looking at updating the travis config to have more complete support, but the testing matrix was looking rather large and I'm not sure if you actually would want the change I was making (I'm not sure what version of Python/frameworks you want to support testing against)

**Comment by waltjones** [comment]
v0.15.0 is released now. https://github.com/rollbar/pyrollbar/releases/tag/v0.15.0

Please feel free to open an issue or PR for the Travis changes.

**Comment by terencehonles** [comment]
Cool, thanks @waltjones !

**Comment by terencehonles** [comment]
> v0.15.0 is released now. https://github.com/rollbar/pyrollbar/releases/tag/v0.15.0
> 
> Please feel free to open an issue or PR for the Travis changes.

I opened #334 in case you didn't see it, and I also opened #335
