### ISSUE TITLE
rollbar spammed by fail safe errors

### ISSUE THREAD

**Issue by AwaishK** [rollbar/pyrollbar#341]
while reporting error on rollbar, I am getting below error. errors on rollbar are being reported at different places in different files, do you know how can I trace back where this is coming from? And how to stop this error to pop up again?

`Failsafe from pyrollbar: payload too large. Original payload may be found in your server logs by searching for the UUID.
`
Below is how I report errors on rollbar, where do I can check the request.body size?
rollbar.report_exc_info()

All the information I get is below, don't know where it is coming from, which script caused this error?
`  "body": {
    "message": {
      "body": "Failsafe from pyrollbar: payload too large. Original payload may be found in your server logs by searching for the UUID."
    }
  }, 
  "failsafe": true, 
  "uuid": "...", 
  "level": "error", 
  "timestamp": 1592460795, 
  "custom": {
    "orig_host": "...", 
    "orig_uuid": "..."
  }, 
  "environment": "production", 
  "framework": "unknown", 
  "internal": true, 
  "notifier": {
    "version": "0.14.6", 
    "name": "pyrollbar"
  }, 
  "metadata": {}
}`

How can I just stop the rollbar to not to send any error in this scenario?

**Comment by danielmorell** [comment]
This should be resolved by the new `v1.1.0-alpha` release.
