### ISSUE TITLE
In django app, normal exceptions like PermissionDenied should not be reported to rollbar

### ISSUE THREAD

**Issue by brettdh** [rollbar/pyrollbar#372]
A 403 response (e.g. due to an authenticated user visiting a URL they are not authorized to access) is an normal response and not indicative of an error in the app. However, the Rollbar middleware for Django reports this exception to Rollbar, and it's not clear to me how (or if) I can configure the middleware to suppress these kinds of spurious errors.

**Comment by bxsx** [comment]
Hi @brettdh and sorry for the late reply.

You can ignore exceptions with event handlers.

In your case, you may need a handler like this:
```python
def ignore_403s_handler(payload, **kw):
    if payload['data']['body']['trace']['exception']['class'] == 'PermissionDenied':
        return False
    
    return payload
```

See docs for details: https://docs.rollbar.com/docs/python#ignoring-items
