### ISSUE TITLE
Not respecting sensitive_post_parameters

### ISSUE THREAD

**Issue by StefanMich** [rollbar/pyrollbar#397]
Django defines a decorator [sensitive_post_parameters](https://docs.djangoproject.com/en/4.0/howto/error-reporting/#filtering-sensitive-information) that marks a parameter as sensitive and therefore should be scrubbed when sent in error reports. 

Rollbar does not respect this decorator, and sends the parameter as it is.

**Comment by pawelsz-rb** [comment]
@StefanMich , this fix is already in master
