### ISSUE TITLE
1.0.0 beta: 'WSGIRequest' object has no attribute 'sensitive_post_parameters'

### ISSUE THREAD

**Issue by brett-dtc** [rollbar/pyrollbar#436]
I was testing out 1.0.0b beta with django 4.2.5 and every error was triggering:

AttributeError at /admin/core/show/
'WSGIRequest' object has no attribute 'sensitive_post_parameters'

Line 188 of rollbar\contrib\django\middleware.py

None of my errors were making it to Rollbar since this exception was processed first and seems to be part of the Rollbar library itself.

I went back to 0.16.3 and it's working

**Comment by danielmorell** [comment]
Hey @brett-dtc, thank you for testing the beta!!! You're awesome! 🚀 

Also, thanks for letting us know about this bug!

We should have the fix out in the next version of the beta shortly.

**Comment by danielmorell** [comment]
The fix for this has been released in `1.0.0b1`.
