### ISSUE TITLE
Documentation for AWS Lambda configuration links to javascript sdk config

### ISSUE THREAD

**Issue by mjperrone** [rollbar/pyrollbar#438]
I am running a python lambda and wish to track errors there using rollbar. This repo links to https://docs.rollbar.com/docs/python as its complete documentation.

On that page, under `Configuration`, the [AWS Lambda](https://docs.rollbar.com/docs/aws-lambda) link points to documentation including only the javascript sdk configuration in lambda.

It seems misleading to link to that from the _python_ docs. I am wondering if that is in error, and what best practices are for using pyrollbar in lambda are. Thanks

**Comment by mjperrone** [comment]
I found my answer here: https://docs.rollbar.com/docs/aws-lambda-1
So I think a link just needs to be updated.

**Comment by brianr** [comment]
Thanks @mjperrone for the report! Fixed the link and moved it to a new url at https://docs.rollbar.com/docs/python-aws-lambda .
