### ISSUE TITLE
ERROR:rollbar:Exception while posting item ApiError(u'could not parse json',)

### ISSUE THREAD

**Issue by mathieuripert** [rollbar/pyrollbar#44]
Hi all,

I am trying to report all exceptions to rollbar using `rollbar.report_exc_info()` but i get the following error:

```
WARNING:rollbar:Got unexpected status code from Rollbar api: 400
Response:
{
  "err": 1,
  "message": "could not parse json"
}
ERROR:rollbar:Exception while posting item ApiError(u'could not parse json',)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rollbar/__init__.py", line 1027, in _send_payload
    _post_api('item/', payload, access_token=payload.get('access_token'))
  File "/Library/Python/2.7/site-packages/rollbar/__init__.py", line 1048, in _post_api
    return _parse_response(path, SETTINGS['access_token'], payload, resp)
  File "/Library/Python/2.7/site-packages/rollbar/__init__.py", line 1115, in _parse_response
    raise ApiError(json_data.get('message') or 'Unknown error')
ApiError: could not parse json
```

I am using rollbar 0.9.6

I inspected sys.exec_info()  but cannot find the reason why it fails. 
Any help would much appreciated !

**Comment by mathieuripert** [comment]
To be more precise, it depends on the exception. Below an example of code that generates the "could not parse json" error.

```
import pandas as pd
import numpy as np
import rollbar

rollbar.init("ACCESS_TOKEN", environment="Debug", enabled=True)

try:
  df = pd.DataFrame({"a":np.arange(1,100)})
  x = df.ix[1000]
except:
  rollbar.report_exc_info(None, None, extra_data={"test":True})
```

However, an exception like the folllowing works perfectly

```
try:
  d = {"key":1}
  d["key2"]
except:
  rollbar.report_exc_info(None, None, extra_data={"test":True})
```

**Comment by coryvirok** [comment]
Thanks for the report, Mathieu. I'm looking into this now.


Cory Virok, @coryvirok <http://twitter.com/coryvirok>
Co-founder and CTO, Rollbar <http://rollbar.com/>

**Comment by rollbardemo** [comment]
I've found the problem. It's that the Python notifier is sending over JSON
that includes NaN as one of the values. I'm looking at fixes now.


Cory Virok, @coryvirok <http://twitter.com/coryvirok>
Co-founder and CTO, Rollbar <http://rollbar.com/>

**Comment by coryvirok** [comment]
I've deployed a fix. Please let me know if this is still a problem.

**Comment by mathieuripert** [comment]
that works! thanks.
In case, the locals are not json serializable, what happens? you exclude them, right?

**Comment by rollbardemo** [comment]
We will try and serialize them but if that doesn't work we send it's type.

https://rollbar.com

On Jan 19, 2015, at 11:10 AM, Mathieu Ripert <notifications@github.com>
wrote:

that works! thanks.
In case, the locals are not json serializable, what happens? you exclude
them, right?

—
Reply to this email directly or view it on GitHub
<https://github.com/rollbar/pyrollbar/issues/44#issuecomment-70544655>.
