### ISSUE TITLE
When will 1.0.0 be released?

### ISSUE THREAD

**Issue by josephgruber** [rollbar/pyrollbar#442]
v1.0.0, which resolves the FastAPI issue, has been in beta for over two months now. Is there any update on when this will be released as a non-beta version?

As a reminder, the FastAPI issue requires your users to pin FastAPI to 0.99.1 while waiting for Rollbar to remediate this issue. This defect in Rollbar is requiring your users to hold back on updating to current versions of FastAPI until it gets fixed.

**Comment by rollbar-bborsits** [comment]
Hey @josephgruber, v1.0.0 will be released in 1-2 weeks.

**Comment by danielmorell** [comment]
Exciting news! It is now released!
