### ISSUE TITLE
RQ support

### ISSUE THREAD

**Issue by mathieuripert** [rollbar/pyrollbar#45]
Guys,

Do you plan to implement a RQ integration?
http://python-rq.org/

Thanks,

**Comment by brianr** [comment]
Hi @mathieuripert -- thanks for the request! We don't currently have plans to implement this ourselves, but we'd happily accept a pull request.

**Comment by brianr** [comment]
Hey @mathieuripert -- RQ support has landed in version 0.9.9 (install via pip). Give it a shot when you can.

Instructions here: https://github.com/rollbar/pyrollbar/blob/master/rollbar/contrib/rq/__init__.py#L2-L30

Thanks!

**Comment by mathieuripert** [comment]
awesome! thanks @brianr

**Comment by arriolac** [comment]
I tried the instructions specified in https://github.com/rollbar/pyrollbar/blob/master/rollbar/contrib/rq/__init__.py#L2-L30 but I'm not able to see the errors in rollbar.

Anyone else have the same issue?

**Comment by arriolac** [comment]
Failure appears to happen in `_post_api`:
```
resp = requests.post(url,
                         data=payload,
                         headers=headers,
                         timeout=SETTINGS.get('timeout', DEFAULT_TIMEOUT),
                         verify=SETTINGS.get('verify_https', True))
```

After this line, Python quits unexpectedly.
