### ISSUE TITLE
Question: gevent with monkey patched sockets, should set handler to blocking?

### ISSUE THREAD

**Issue by james-m** [rollbar/pyrollbar#5]
[question / clarification]

Hello--

We're a gevent shop and very interested in rollbar--there is an example of using rollbar with a gevent wsgi server (https://rollbar.com/docs/project/1888/items_python/). I was expecting the rollbar.init() call in this example to actually set the handler to blocking, which if you've monkey patched socket (as I would expect is the common case when using gevent), it of course only appears to be blocking. 

Baring this I was expecting MAYBE some part of the rollbar code to detect gevent and maybe monkey patch threading (I say "MAYBE" just because such a technique seems way way to automagical to me, but I guess it's conceivably an approach to take...)

Anyways, does this sound sane? Have you guys done any testing around this scenario? It seems like spawning a new thread for every rollbar report call is wasteful and not very "geventy"....

**Comment by coryvirok** [comment]
Closing this since it's so old and there haven't been any updates in a few years. Please reopen as necessary.
