### ISSUE TITLE
When rb has exception policy

### ISSUE THREAD

**Issue by stevepeak** [rollbar/pyrollbar#56]
Rollbar, itself, seems to be having problem that I cannot seem to solve (see traceback below). Either way I would suggest that if rb has an exception that you catch it and stdout the original traceback and the rollbar exception. I'm having trouble debuging my code when rb fails to report and nothing is printed. I've seen some other errors before like 500 server errors and such, which is understandable, but I loose all my tracebacks that I need...

``` python
Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/rollbar/__init__.py", line 711, in _add_locals_data
    args.append(_local_repr(local_vars[named_arg]))
KeyError: 'connection'
```

``` diff
-    args.append(_local_repr(local_vars[named_arg]))
+    args.append(_local_repr(local_vars.get(named_arg, None)))
```

[Related line](https://github.com/rollbar/pyrollbar/blob/e80b15161ba06bf01bc5e0d30e24f9836762a482/rollbar/__init__.py#L711)

Thanks!

**Comment by brianr** [comment]
Hi @stevepeak , thanks for the report!

Are you sure that the original exception (from your application) isn't being reported? If an exception happens in `_add_locals_data`, it should result in that exception being logged, and then locals simply won't be collected for that report...

Here's the `try` that encloses the line you referenced: https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L695
Here's where the exception is logged (I think this is the exception you pasted the traceback for): https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L739

**Comment by stevepeak** [comment]
Thank you for the prompt reply. I see the wrapper which is great! Sorry for my confusion. 

I was hoping that Rollbar would also log the original traceback. Like in this example below:

### Currently
```python
try:
  int('a')
except:
  # lets say this fails...
  rollbar.report_exc_info()
>>> Error while extracting arguments from frame. Ignoring.
```

Would it be possible to add a `Uncaught exception notice` at L739? Otherwise I have to do this everywhere.

```python
try:
  int('a')
except:
  # lets say this fails...
  rollbar.report_exc_info()
  log.exception("Uncaught exception", exc_info=(original_typ, original_value, original_tb))
```

**Comment by rokob** [comment]
This is pretty old and the code has moved on from when this question was asked. However, the question itself still doesn't make a lot of sense. The "failure" that happens at https://github.com/rollbar/pyrollbar/blob/e80b15161ba06bf01bc5e0d30e24f9836762a482/rollbar/__init__.py#L739 does not stop Rollbar from reporting the item. It only means that the particular frame will not have local variables attached. The message `Error while extracting arguments from frame. Ignoring.` only means that this frame is having the locals ignored, the overall uncaught exception is still sent.
