### ISSUE TITLE
log arguments not displayed properly

### ISSUE THREAD

**Issue by expntly** [rollbar/pyrollbar#58]
[It might be the wrong place to post the issue, let me know where to go if that's the case.]

I use RollbarHandler.  I noticed that doing logger.error("arg %s", "foo") shows up as literally "arg %s" on the items I see on rollbar.com.  Am I missing something?  I would've expected rollbar to show "arg foo".  The args are nowhere to be found on the web interface.

I see here https://github.com/rollbar/pyrollbar/blob/master/rollbar/test/test_loghandler.py#L44 that the args should be passed, so I guess the issue has more to do with the way rollbar's web frontend displays the item?

Thanks!

**Comment by expntly** [comment]
Actually I see the args in message.args.  Would be great to have the string formatted properly though.  Anyway I'll close the issue, don't think this has to do with pyrollbar.

**Comment by coryvirok** [comment]
That is confusing. I'll chat with the team and see if there's a way we can make this better.

**Comment by mikeengland** [comment]
I am also experiencing this issue. The main dashboards/items are just showing things like `#196 AttributeError: Internal Server Error: %s`, however we need to see the actual args that are attached to this error instead of just '%s'.
