### ISSUE TITLE
Support for Python 3.4

### ISSUE THREAD

**Issue by Marco-Santoni** [rollbar/pyrollbar#66]
I have tried to install and run `rollbar` with Python 3.4.3, and it worked nicely. However, the [readme](https://github.com/rollbar/pyrollbar#requirements) states that only 2.6, 2.7, 3.2 or 3.3 are supported.

Is just the readme outdated? Or is Python 3.4 not tested yet?

**Comment by brianr** [comment]
Hi @Marco-Santoni - thanks for pointing that out. This is just the readme being out of date; we do run the tests on python 3.4 and they're passing: https://travis-ci.org/rollbar/pyrollbar

We'll update the readme. Thanks!
