### ISSUE TITLE
rollbar.init() silently ignores passed options if called multiple times

### ISSUE THREAD

**Issue by brianr** [rollbar/pyrollbar#72]
`rollbar.init()` keeps track of whether it has been initialized, and only runs the body of the function if it has not yet been initialized. This means that if you call it multiple times -- perhaps unintentionally, i.e. you have a complex app within multiple `rollbar.init()` calls -- the options you pass after the first time are ignored, and there's nothing to tell you so.

I think we should:

- at the very least: log a warning when rollbar.init() is called more than once
- possibly: update rollbar.init() to not ignore options passed when it is called subsequent times. Or, make some other change to this interface to make it easier to use correctly.

**Comment by coryvirok** [comment]
Seems like the next thing to do is implement the new notifier interface. `rollbar.configure({})` will respect multiple "initializations".

**Comment by elvis-macak** [comment]
the same issue https://github.com/rollbar/pyrollbar/issues/79

most time, we just call `rollbar.report_exc_info`, in that method, we can pass an arguments called `payload_data`, we can do as much as we can with this.

currently, it cannot accepts access_token, hope can sepcify in it

**Comment by elvis-macak** [comment]
like this
<pre>
payload = {"access_token": ROLLBAR_ACCESS_TOKEN}
rollbar.report_exc_info(payload_data=payload)
</pre>

**Comment by dlsteuer** [comment]
Fixed and released in 0.10.1, please upgrade if you are still having issues.

**Comment by DogaCUlupinar** [comment]
i am on rollbar 0.16.3 and reporting to a different project through setting the access token in `payload_data` is not working. This is because the access token is always set from the settings: https://github.com/rollbar/pyrollbar/blame/master/rollbar/__init__.py#L1495
