### ISSUE TITLE
HTTP/HTTPS connection causing application to crash

### ISSUE THREAD

**Issue by alexwidener** [rollbar/pyrollbar#74]
Application: Autodesk Maya 2015 SP5 (runs Python 2.7.3)
Internal Python: 2.7.3
pyrollbar: 0.9.14 & 0.10.0

When using rollbar with either https or http as the endpoint url, rollar will intermittently cause the application to crash. 

It's been determined to be the http/https portion through the following: 
 - Launching the application(Maya) in debug mode causes the application to never crash while reporting Rollbar issues. (unknown as to why)
 - Re-enabling rollbar using agent as a handler results in all logs getting written to disk, never crashing.
 - Re-enabling rollbar in https causes the application to crash either before the 1st event is filed to rollbar, or between the 1st and 4th event. https causes a crash before the 5th event. 
 - Re-enabling rollbar in http causes the application to crash by the 5th or 6th event(hasn't crashed before the 1st event is filed). Thus, http is ironically more secure than https in this situation :)

Because of the event occurring in both https and http, we can deduce that it's not due to OpenSSL, and because it doesn't occur in agent mode, we can narrow it down to the HTTP/HTTPS connection.

The current workaround plan is to use agent and potentially use logstash to communicate with rollbar, as rollbar-agent is not currently on Windows which is tied to this issue: rollbar/rollbar-agent#25

The only application currently tested is Autodesk Maya, however this would eventually be deployed to all applications in the environment. Therefore, relying on an unstable http connection while inside the application introduces a whole bevvy of other problems.

**Comment by coryvirok** [comment]
Hi Alex,

Sorry for the problems you're seeing. Do you have any traceback information when the app crashes?

**Comment by alexwidener** [comment]
Hi! Sent through e-mail to Chris.

**Comment by alexwidener** [comment]
For anyone in the future: the fix appears to have been to set the handler to 'blocking'. Cory also recommended to disable local variable gathering, so this would have been the code:

`rollbar.init('ACCESS_TOKEN', handler='blocking', locals={'enabled': 'false'})`
