### ISSUE TITLE
multiple rollbar.init

### ISSUE THREAD

**Issue by elvis-macak** [rollbar/pyrollbar#79]
I got some projects, let's name them projectA, projectB. and each one has it's own rollbar init calls, of cousre with different access_token.

and now I have a new projectC, that will depends on projectA and projectB. that means `rollbar.init` will call ether in projectA, projectB, projectC. as the rollbar code, the latest one will overwritte the previous.

as the code beblow, can I use access_token with my `payload_data` if I passed in passed in, not use it directly from SETTINGS?
<pre>
def _build_payload(data):
    """
    Returns the full payload as a string.
    """
    payload = {
        'access_token': SETTINGS['access_token'],
        'data': data 
    }
    return payload
</pre>

**Comment by dlsteuer** [comment]
Duplicate of #72
