### ISSUE TITLE
JSON body causes Rollbar to reject submissions

### ISSUE THREAD

**Issue by oyiptong** [rollbar/pyrollbar#82]
Due to https://github.com/rollbar/pyrollbar/blob/ac8264cf90ef12bc46f704b97731ee6ff023fb03/rollbar/__init__.py#L1048, Rollbar rejects messages that have message bodies that are objects, not strings.

According to https://rollbar.com/docs/api/items_post/, the message should contain the raw POST body.

**Comment by coryvirok** [comment]
I have updated our server to correct this on our end so this shouldn't be a problem anymore.
